defalut_params:
  project: '' # comment
  aggregate_peak_method: 'nearest'
  cell_number_per_group: 50
  cell_cutoff: 20
  peak_confidence: 5
  bg_iter: 'auto'
  reference: True
  thread: 16
  yes_confirm: False
  clean: False

index:
  human_chip_index: ''
  human_motif_index: ''
  mouse_chip_index: ''
  mouse_motif_index: ''