defalut_params:
  project: '' # comment
  cell_number_per_group: 50
  peak_confidence: 5
  bg_iter: 'auto'
  reference: True
  thread: 16
  yes_confirm: False
  clean: False

index:
  human_chip_index: ''
  human_chip_index_dataset_number: ''
  human_motif_index: ''
  human_motif_index_dataset_number: ''
  mouse_chip_index: ''
  mouse_chip_index_dataset_number: ''
  mouse_motif_index: ''
  mouse_motif_index_dataset_number: ''