defalut_params:
  project: '' # comment
  # cell_number_per_group: 50
  # peak_confidence: 5
  # reference: True
  thread: 16
  yes_confirm: False
  clean: False

index:
  human_tf_index: ''
  mouse_tf_index: ''

